### PR TITLE
Add ActiveRecord example

### PR DESCRIPTION
**Pull request by jordanlewis**
This doesn't yet work on CockroachDB, but it does work against Postgres.

Issues:

1. Rails prints some warnings to stderr, which the test framework doesn't allow
2. There's a few Rails PRs that haven't made it into a release yet that are required for compatibility
3. We don't support savepoints yet
4. Rails adds some extra tables (`schema_migrations`, `ar_internal_metadata`) that are rejected by the test framework

cc @tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/9)

### CODE REVIEW

**Comment by jordanlewis** [comment]
PTAL, this is working now with tests.

**Comment by tamird** [comment]
Reviewed 67 of 67 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Makefile, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeihuJIJBxHz0kOOxbD:-KeihuJIJBxHz0kOOxbE:bnn86jm) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/Makefile#L19)):*
> ```Makefile
> 
> GO ?= go
> POSTGRES_TEST_TAG ?= 20170308-0001
> ```

0002 now?

---

*[ruby/activerecord/app/controllers/products_controller.rb, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiZ4Y4PZ0_JLIgv0V:-KeiiZ4Y4PZ0_JLIgv0W:b-1zjryo) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/controllers/products_controller.rb#L26)):*
> ```Ruby
>     o = Order.find(params[:order_id])
>     p = Product.find(params[:product_id])
>     o.products<<p
> ```

what's this?

as mentioned elsewhere, this method is highly unusual.

---

*[ruby/activerecord/app/models/order.rb, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keik0vw4uKxpC61pmd2:-Keik0vw4uKxpC61pmd3:bkq4q1v) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/models/order.rb#L6)):*
> ```Ruby
>   belongs_to :customer
> 
>   has_and_belongs_to_many :products, join_table: 'order_products'
> ```

the join table should be called `orders_products`, i think. you're fighting the convention when you specify the join table name.

as mentioned elsewhere, I think you should also have the intermediate model.

---

*[ruby/activerecord/config/routes.rb, line 4 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiukOe68PFdCvFnTc:-KeiiukOe68PFdCvFnTd:bu3xd58) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L4)):*
> ```Ruby
>   get :ping, to: 'ping#ping'
> 
>   resources :customers, path: '/customer', except: [:edit, :new]
> ```

why did you need the :path argument to any of these? do the defaults not work? they would be plural, though.

---

*[ruby/activerecord/config/routes.rb, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keij7ScA5Ov-1rKn-2x:-Keij7SdOimispn3_XJH:b-2kghph) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L7)):*
> ```Ruby
>   resources :products,  path: '/product',  except: [:edit, :new]
>   resources :orders,    path: '/order',    except: [:edit, :new] do
>     post 'product', to: 'products#add_product_to_order'
> ```

this is pretty unusual; you probably want a model for the join table instead, and another resource "orders_products" (or whatever the name would be) that you can just create.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeijRevOecEWI1goJSt:-KeijRevOecEWI1goJSu:b-pgmd8k) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L5)):*
> ```Ruby
>     create_table :customers do |t|
>       t.string :name, null: false
> ```

random newline

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeikORILJzpbZeIbP-m:-KeikORJ-nQhimLWEvWC:bojf3o4) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L14)):*
> ```Ruby
> 
>     create_table :orders do |t|
>       t.decimal :subtotal, precision: 18, scale: 2, null: false
> ```

how come the subtotal is needed? isn't it the sum over the line items?

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeijYwsfmEdZ6kEJmht:-KeijYwsfmEdZ6kEJmhu:b-oi1sdh) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L27)):*
> ```Ruby
>     # Deleting an order deletes its line items
>     add_foreign_key :order_products, :orders
>     # Deleting a product shouldn't delete its line items
> ```

can you help me understand why these seemingly identical `add_foreign_key` calls have different comments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9)*

**Comment by jordanlewis** [comment]
TFTR

---

Review status: 66 of 67 files reviewed at latest revision, 8 unresolved discussions.

---

*[Makefile, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeihuJIJBxHz0kOOxbD:-Kej0XHKvB0Nb1OPi9l-:bv6gyfs) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/Makefile#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

0002 now?
</blockquote></details>

I didn't regenerate the image, so no. Also, 0001 was the time that I made the image, not its serial number, so your comment confused me for a moment

---

*[ruby/activerecord/app/controllers/products_controller.rb, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiZ4Y4PZ0_JLIgv0V:-Kej0ga9ib2tKBjvzhRM:bl17foq) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/controllers/products_controller.rb#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's this?

as mentioned elsewhere, this method is highly unusual.
</blockquote></details>

AFAIK this is how you add a model to a has_many collection? http://techspry.com/ruby_and_rails/active-records-or-push-or-concat-method/ 

Doesn't seem unusual to me because it behaves as I expect.

---

*[ruby/activerecord/app/models/order.rb, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keik0vw4uKxpC61pmd2:-Kej0zU459TC1dkYOi1c:bhnps27) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/models/order.rb#L6)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the join table should be called `orders_products`, i think. you're fighting the convention when you specify the join table name.

as mentioned elsewhere, I think you should also have the intermediate model.
</blockquote></details>

There's a reason I fought convention here. It's because the ORM test harness that Nathan made expects the table to be called order_products. I'd rather not change the test harness to accommodate this convention.

---

*[ruby/activerecord/config/routes.rb, line 4 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiukOe68PFdCvFnTc:-Kej18rKgYeSDqKRaNt5:b-9kpmo9) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L4)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why did you need the :path argument to any of these? do the defaults not work? they would be plural, though.
</blockquote></details>

The defaults do not work because the endpoints must be singular to satisfy the constraint of the test harness.

---

*[ruby/activerecord/config/routes.rb, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keij7ScA5Ov-1rKn-2x:-Kej1DkLLR0H_H13xndq:blowm7s) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is pretty unusual; you probably want a model for the join table instead, and another resource "orders_products" (or whatever the name would be) that you can just create.
</blockquote></details>

I tried this at first by making a line items model. I encountered a lot of difficulties on the way, and decided to use a join table instead. It's easier this way.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeijRevOecEWI1goJSt:-Kej22AXB1wMd-Rwabkv:b-896fix) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L5)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

random newline
</blockquote></details>

Done.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeikORILJzpbZeIbP-m:-Kej1iqMmyvj10AnsJvu:b-17g4k9) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L14)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come the subtotal is needed? isn't it the sum over the line items?
</blockquote></details>

Because that's what the test framework expects.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeijYwsfmEdZ6kEJmht:-Kej1lXKU4cITYoiOOCH:b-42k3ub) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you help me understand why these seemingly identical `add_foreign_key` calls have different comments?
</blockquote></details>

It's a mistake, thanks for catching. Originally I had a cascade statement here until I realized that CockroachDB doesn't support that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-:-Kej2FnHPnZ9w4Y7HfM7:bb73zsl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ruby/activerecord/app/controllers/products_controller.rb, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiZ4Y4PZ0_JLIgv0V:-Kej4mAVx4kDLYZuc7o8:b-6s3ffr) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/controllers/products_controller.rb#L26)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

AFAIK this is how you add a model to a has_many collection? http://techspry.com/ruby_and_rails/active-records-or-push-or-concat-method/ 

Doesn't seem unusual to me because it behaves as I expect.
</blockquote></details>

Ah, I see. The `<<` messes with syntax highlighting here, which is what confused me. If you could replace it with `.push`, I think it'd be clearer.

The second part about this being unusual is objective; this is not how people write Rails apps. I appreciate that it behaves how you expect, but it doesn't exercise the machinery that I, if I were considering Rails on CRDB, would want to see exercised.

---

*[ruby/activerecord/app/models/order.rb, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keik0vw4uKxpC61pmd2:-Kej5HUd1XUz5Gbml1Zp:bvg46ox) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/models/order.rb#L6)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There's a reason I fought convention here. It's because the ORM test harness that Nathan made expects the table to be called order_products. I'd rather not change the test harness to accommodate this convention.
</blockquote></details>

That's fine. Perhaps this deserves a comment, but perhaps not.

---

*[ruby/activerecord/config/routes.rb, line 4 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiukOe68PFdCvFnTc:-Kej5NU6RpO39RKkTUL2:baw9p5m) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L4)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The defaults do not work because the endpoints must be singular to satisfy the constraint of the test harness.
</blockquote></details>

Perhaps a comment.

---

*[ruby/activerecord/config/routes.rb, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keij7ScA5Ov-1rKn-2x:-Kej5PhFz1En0-w5ql6p:bxmec74) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L7)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I tried this at first by making a line items model. I encountered a lot of difficulties on the way, and decided to use a join table instead. It's easier this way.
</blockquote></details>

To be clear, the intermediate model would sit on the join table as-is. I'm happy to help you figure out how to make it work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ruby/activerecord/app/controllers/products_controller.rb, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiZ4Y4PZ0_JLIgv0V:-Kej75hr3h6ajKldPasf:btoefwh) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/controllers/products_controller.rb#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, I see. The `<<` messes with syntax highlighting here, which is what confused me. If you could replace it with `.push`, I think it'd be clearer.

The second part about this being unusual is objective; this is not how people write Rails apps. I appreciate that it behaves how you expect, but it doesn't exercise the machinery that I, if I were considering Rails on CRDB, would want to see exercised.
</blockquote></details>

As a Rails noob, I have no idea what's wrong with this method! It seems perfectly clear to me. It seems you have a pretty strong opinion about it though - since I have no idea how to use Rails, maybe you could provide an example of what this should look like?

---

*[ruby/activerecord/config/routes.rb, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keij7ScA5Ov-1rKn-2x:-Kej7RiQcWpQH_vqoxYS:b-rwotcj) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

To be clear, the intermediate model would sit on the join table as-is. I'm happy to help you figure out how to make it work.
</blockquote></details>

Yeah I tried to make this work before and gave up. Like I said, this method seems simpler and clearer to me - but I guess that's because I don't know what Rails apps are supposed to look like in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ruby/activerecord/app/controllers/products_controller.rb, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-KeiiZ4Y4PZ0_JLIgv0V:-KejA7C9ansxVJvJT97-:bne9juy) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/app/controllers/products_controller.rb#L26)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

As a Rails noob, I have no idea what's wrong with this method! It seems perfectly clear to me. It seems you have a pretty strong opinion about it though - since I have no idea how to use Rails, maybe you could provide an example of what this should look like?
</blockquote></details>

Sure, I'll push a commit with this suggestion.

---

*[ruby/activerecord/config/routes.rb, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9#-Keij7ScA5Ov-1rKn-2x:-KejA5ZkpMTR5P87A7qm:b-z1fr5d) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1e01201e3e33791e47140f9403d903a603758782/ruby/activerecord/config/routes.rb#L7)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah I tried to make this work before and gave up. Like I said, this method seems simpler and clearer to me - but I guess that's because I don't know what Rails apps are supposed to look like in the first place.
</blockquote></details>

I'll push a commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/9)*

**Pull request merged**
