### PR TITLE
really convince Docker not to create any directories as root

### PR DESCRIPTION
**Pull request by benesch**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/24)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM

**Comment by tamird** [comment]
Instead of this, can we only run `make deps` outside the container? That's
the approach I took in the examples-go repository.

**Comment by benesch** [comment]
We do only run `make deps` outside the container. The problem is that we mount `$GOPATH/src` at `docker_root/USERNAME/go/src`, which doesn't exist at mount time, so Docker creates it as root.

**Comment by benesch** [comment]
This just failed with a `sqlalchemy.exc.OperationalError: (psycopg2.extensions.TransactionRollbackError) restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn "sql txn" id=c8e9f496 key=/Table/0/0 rw=true pri=0.00258759 iso=SERIALIZABLE stat=PENDING epo=0 ts=1495218755.049911913,1 orig=1495218755.017425897,0 max=1495218755.017425897,0 wto=false rop=false seq=6` error. 🤦‍♂️ Missing retry loop somewhere. Rerunning.

**Comment by benesch** [comment]
Oh, you mean `godeps` _and_ `ormdeps`? The whole point is that only the docker image has Node/Ruby/Java/whatever, isn't it?

**Comment by benesch** [comment]
Merging to unbrick TeamCity, but happy to address as a follow up. (I'm still not entirely sure what you mean.)

**Comment by tamird** [comment]
Ah, yeah maybe that's true, and that's a bummer.

> The problem is that we mount $GOPATH/src at docker_root/USERNAME/go/src

I haven't looked at this diff (or the previous one) but there are two
docker behaviors to be mindful of:

- mounted host directories that don't exist at mount time are created by
the docker daemon, so they are created as root
- files/directories that are created by processes inside the container are
owned by the container user, which is why we have the passwd hacks

Apologies if this isn't adding anything new. My point is that fetching go
dependencies can be done outside the container, and sharing GOPATH/src is
safe as long as you don't `go get` inside the container. For the
Ruby/Java/etc. dependencies, it may be just fine to not cache them on the
host, which would avoid these problems.

**Comment by benesch** [comment]
Right, definitely. The problem is a nested mount, which creates a stray directory on the host as root. Creating that directory before Docker does, as done in this PR, solves the problem.

You're right that we wouldn't have the nested mount if we didn't cache the home directory, but it's real annoying to have to reinstall the deps every time you run `make dockertest` when developing locally.

**Pull request merged**
