### PR TITLE
activerecord: update to rails 5.1; adapter 0.2.0

### PR DESCRIPTION
**Pull request by jordanlewis**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmTf_B3KOgajQWDDLrA:-KmTf_B3KOgajQWDDLrB:b-b45pn1) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L1)):*
> ```Ruby
> class CreateSchema < ActiveRecord::Migration[5.1]
> ```

whoa, TIL.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmTfchS-kywgiwnkaGf:-KmTfchS-kywgiwnkaGg:b8lv8j3) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L2)):*
> ```Ruby
> class CreateSchema < ActiveRecord::Migration[5.1]
>   disable_ddl_transaction!
> ```

Weren't we going to move this to the adapter? Looks like we just need to implement a method https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L296

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29)*

**Comment by jordanlewis** [comment]
Done

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ruby/activerecord/Gemfile, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmYfXxSMjqPvhNubwkW:-KmYfXxSMjqPvhNubwkX:b7ae6ap) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/Gemfile#L41)):*
> ```Ruby
> end
> 
> # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
> ```

why remove this? doesn't matter AFAICT

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-:-KmYfhLrr9iB5UgSJTha:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ruby/activerecord/Gemfile, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmYfXxSMjqPvhNubwkW:-KmYgihHlm4gEvyeSF1q:b-18y034) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/Gemfile#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why remove this? doesn't matter AFAICT
</blockquote></details>

It was causing some warnings during build. shrug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmTf_B3KOgajQWDDLrA:-KmYgmHhk5ljP5TB4p93:b-896fix) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

whoa, TIL.
</blockquote></details>

Done.

---

*[ruby/activerecord/db/migrate/20170207160810_create_schema.rb, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29#-KmTfchS-kywgiwnkaGf:-KmYgm4U5YN-bRetYySA:b-896fix) ([raw file](https://github.com/cockroachdb/examples-orms/blob/1bc13774cadd3b0879e50715cf684b3e8bc60595/ruby/activerecord/db/migrate/20170207160810_create_schema.rb#L2)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Weren't we going to move this to the adapter? Looks like we just need to implement a method https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L296
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/29)*

**Comment by jordanlewis** [comment]
TC isn't reporting back to this repo because of a config change, so I'm going to force merge this.

**Pull request merged**
