### PR TITLE
vendor: vendor deps

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/25)

### CODE REVIEW

**Comment by bdarnell** [comment]
Should these go in `go/vendor` instead of the top-level `vendor`? There's more than just go code in this repo.

**Comment by dt** [comment]
The common test driver in /testing is in go too though, and would be a little strange to move into go/?

**Comment by bdarnell** [comment]
OK, didn't realize that. Carry on then. I mainly wanted to avoid a precedent for putting Gemfiles and everything else in the top level of the repo.

**Comment by dt** [comment]
yeah, fair enough.

I looked at potentially giving the test code its own `vendor` and then the go-specific example its own `vendor` which would have been nice and clean... but the common test driver depends on the go ORM's models, so there isn't really much separation to maintain anyway.

**Pull request merged**
