### PR TITLE
activerecord: Setup initial project structure, schema, and db connection

### PR DESCRIPTION
**Pull request by nvanbenschoten**
This is currently blocked on use of **pg_type** in the Postgres connection adapter. It also is having issue with:
- use of the [alias type **regprocedure**](https://www.postgresql.org/docs/8.1/static/datatype-oid.html)
- use of unsupported session variables like `SET client_min_messages TO 'warning'`

Most of the boilerplate here is coming from the `rails new` command.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/3)

### CODE REVIEW

**Comment by tamird** [comment]
What's the acceptance criteria here? We need some CI integration, I think.

**Comment by nvanbenschoten** [comment]
What is the point of CI integration if it doesn't run yet (see blockers above)? I guess we could assert that the project compiles, but that doesn't seem like a hard prerequisite for these initial changes. I figured it was better to push incremental commits than to land a single large PR when we get an ORM working, but this of course means that we're going to have an intermediate "in-construction" state.

**Comment by bdarnell** [comment]
It's good to have the incremental commits available for ease-of-review when the working code is merged, but I don't think it makes sense to merge non-working code into master. The name of this repo says "examples" after all; end users should be able to take anything from the master branch of this repo and run it.

**Comment by benesch** [comment]
This can be closed, right?

**Pull request closed without merging**
