### PR TITLE
Update README with install instructions

### PR DESCRIPTION
**Pull request by rmloveland**
Figure this might save someone some trial and error.

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm: with just a small change

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/examples-orms/46#-LCjjGZ_9MbdMfESTsI5:-LCjjGZ_9MbdMfESTsI6:b-dfnhax) ([raw file](https://github.com/cockroachdb/examples-orms/blob/7c28feba239eec15eb597f9996bea54a711d17a5/README.md#L14)):*
> ```Markdown
> Clone this repo into your `$GOPATH` manually, e.g.,
> 
> ```
> ```

add `bash`  here right after the 3 tics, and to all the other sections as well.  This will add correct highlighting in github.

\`\`\`bash


Might as well do this for the whole readme.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/46#-:-LCjjaSO1H8t51sLxZcU:byiom4x)*

**Comment by rmloveland** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/examples-orms/46#-LCjjGZ_9MbdMfESTsI5:-LCnZqrq8My3SO9H6KyS:b-ao4pv0) ([raw file](https://github.com/cockroachdb/examples-orms/blob/7c28feba239eec15eb597f9996bea54a711d17a5/README.md#L14)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

add `bash`  here right after the 3 tics, and to all the other sections as well.  This will add correct highlighting in github.

\`\`\`bash


Might as well do this for the whole readme.
</blockquote></details>

Fixed - thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/46)*

**Comment by rmloveland** [comment]
Not sure if needed, but:

bors r+

**Comment by rmloveland** [comment]
@BramGruneir Thank you for the review!

It looks like the CI wants something else to make this merge-able.  Do you know how to appease it?

**Comment by BramGruneir** [comment]
I don't know if we use bors for this repo.  @couchand 
And I don't know why the teamcity build didn't start either.

**Comment by jordanlewis** [comment]
Bors isn't used for this repo. And it seems to have some weird check configuration. I can fix it, but in the meantime since yoou do have a passing build you can go ahead and merge.

**Comment by rmloveland** [comment]
Thanks for checking on this @jordanlewis !

Unfortunately the merge button is grayed out for me and there's a message about required statuses:

screenshot 2018-05-21 13 10 03

**Comment by BramGruneir** [comment]
@rmloveland Merged it for you.

**Pull request merged**
