### PR TITLE
Updated view retry function control flow, error exceptions

### PR DESCRIPTION
**Pull request by ericharmeling**
Follow-up on https://github.com/cockroachlabs/support/issues/654.

After we merge here, I'll propagate to docs.

### CODE REVIEW

**Comment by rafiss** [comment]
error log:

```
  File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 40, in <module>
    class CustomersView(View):
  File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 49, in CustomersView
    @atomic
  File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 22, in retry
    return view(*args, **kwargs)
TypeError: 'int' object is not callable
```

so it thinks `view` is an int?

**Comment by ericharmeling** [comment]
> error log:
> 
> ```
>   File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 40, in <module>
>     class CustomersView(View):
>   File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 49, in CustomersView
>     @atomic
>   File "/home/agent/go/src/github.com/cockroachdb/examples-orms/python/django/cockroach_example/views.py", line 22, in retry
>     return view(*args, **kwargs)
> TypeError: 'int' object is not callable
> ```
> 
> so it thinks `view` is an int?

I didn't update the decorator calls - my bad. They were all taking unassigned input that was meant to be for `num_retries`. Removed those `int`s, as they were all the default value anyways (i.e., `3`).

Hopefully it works now.

**Comment by ericharmeling** [comment]
@rafiss Ping on re-review.

@florence-crl Does this address the customer request filed in https://github.com/cockroachlabs/support/issues/654?

**Comment by florence-crl** [comment]
I defer to @rafiss to determine whether [his clarifying comment](https://github.com/cockroachlabs/support/issues/654#issuecomment-725571765) is addressed/included in this update.

**Review by rafiss — APPROVED** [review]
lgtm! thanks

**Pull request merged**
