### PR TITLE
Support assigning random ports to the appserver

### PR DESCRIPTION
**Pull request by andreimatei**
... to allow stressing the sqlalchemy test.
This commit adds a flag to the test framework for the appserver flag.
That flag is passed to the language-specific makefile, and only the
SQLAlchemy one has support for it.

cc @jordanlewis

### CODE REVIEW

**Comment by andreimatei** [comment]
I believe it used to work for me, but now, on the master of this repo, when I run
```
go test -v -run "TestSQLAlchemy" ./testing
```
I get endless `2017/07/05 13:30:34 waiting for app server port to become available`. Does it work for you?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-:-KoIpeZmaTrVQFtGU_rb:b-f6h1if)*

**Comment by cuongdo** [comment]
I'll review the changes later today, but your command-line works for me with the latest master code and both Python 2.7.13 and Python 3.5.2.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-:-KoIzjL3N1qeRKaLU8qG:b9cqgm8)*

**Comment by cuongdo** [comment]
:lgtm: w/ minor comments

Also, thanks for the cleanups.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[testing/main_test.go, line 97 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-KoNGhvCr5F6BAt0mcF2:-KoNGhvCr5F6BAt0mcF3:b6092vl) ([raw file](https://github.com/cockroachdb/examples-orms/blob/35cd7554bf81a5733857fbdd68ceecf0ce92a717/testing/main_test.go#L97)):*
> ```Go
> 	cmd := exec.Command(
> 		"make", "start", "-C", app.dir(), "ADDR="+dbURL.String(),
> 		fmt.Sprintf("APPSERVER_PORT=%d", appServerPort),
> ```

can you use `log.Printf` for consistency (and timestamps)?

---

*[testing/main_test.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-KoNG_sgfOoGKnxG8TYf:-KoNG_sh9sui7six-W6G:b6092vl) ([raw file](https://github.com/cockroachdb/examples-orms/blob/35cd7554bf81a5733857fbdd68ceecf0ce92a717/testing/main_test.go#L139)):*
> ```Go
> 
> 	for waited := time.Duration(0); ; waited += waitDelay {
> 		fmt.Printf("test looping. command %s status: %s\n", cmd.Args, cmd.ProcessState)
> ```

can you use `log.Printf` for consistency (and timestamps)?

---

*[testing/main_test.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-KoNH3vlbMcJ02QVbKvF:-KoNH3vlbMcJ02QVbKvG:bgthh8z) ([raw file](https://github.com/cockroachdb/examples-orms/blob/35cd7554bf81a5733857fbdd68ceecf0ce92a717/testing/main_test.go#L161)):*
> ```Go
> 	if appServerPort == 0 {
> 		rand.Seed(time.Now().UTC().UnixNano())
> 		appServerPort = 10000 + rand.Intn(30000)
> ```

There's a slight chance that the port is not available. Maybe try connecting to the port to ensure nothing is bound to it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-:-KoNHJwZf2VpYiCNEmFd:b22q6t1)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[testing/main_test.go, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30#-KoNH3vlbMcJ02QVbKvF:-KoNbZiKvdkHrv8rrQTd:bzeiupd) ([raw file](https://github.com/cockroachdb/examples-orms/blob/35cd7554bf81a5733857fbdd68ceecf0ce92a717/testing/main_test.go#L161)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

There's a slight chance that the port is not available. Maybe try connecting to the port to ensure nothing is bound to it?
</blockquote></details>

The ideal way to handle this would be to either ask the server to bind to port zero and report back what port it used, or to bind the port here in the parent process and pass the file descriptor to the child. But this is probably not very well supported across the frameworks we want to test.

A nearly-reliable way to do this is (as long as the child process uses SO_REUSEADDR, which is common) to bind to port zero, find out what port you were assigned, then close that port and ask the child process to use it. In most cases it will be a long time before the kernel cycles back around to the same port. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/examples-orms/30)*

**Pull request closed without merging**
