### PR TITLE
gopg: add an example app using go-pg

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds an implementation of the example app using go-pg
ORM. The code was adapted from GORM example with some modifications.

Also, the testing harness is slightly modified to allow for
nil slices be returned when retrieving the data before creation.

Fixes: https://github.com/cockroachdb/cockroach/issues/41398.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping.

**Comment by asubiotto** [comment]
@rafiss I'll let you review this since this is your area. Let me know if you'd like me to take a look as well.

**Comment by rafiss** [comment]
I'm taking a look now. It seems like it works locally, but fails in TeamCity with:

```
main_test.go:216: Get http://localhost:6543/ping: dial tcp 127.0.0.1:6543: getsockopt: connection refused
```

That seems to mean that it can't connect to that REST API server.

**Comment by yuzefovich** [comment]
The actual problem here is that the test suite cannot find `gopg` binary:
```
[17:53:05][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] make[1]: Entering directory '/home/agent/go/src/github.com/cockroachdb/examples-orms/go/gopg'
[17:53:05][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] GO111MODULE=on go get github.com/go-pg/pg/v9
[17:53:06][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] package github.com/go-pg/pg/v9: cannot find package "github.com/go-pg/pg/v9" in any of:
[17:53:06][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] 	/usr/local/go/src/github.com/go-pg/pg/v9 (from $GOROOT)
[17:53:06][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] 	/home/agent/go/src/github.com/go-pg/pg/v9 (from $GOPATH)
[17:53:06][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] Makefile:22: recipe for target 'start' failed
[17:53:06][TestGORM/SecondRun/RetrieveFromAPIAfterRestart] make[1]: *** [start] Error 1
```
This must be an issue with interaction between test setup and Go modules, but I have no idea where to look at. Maybe folks from Dev-Infra would know?

@bobvawter @jlinder the problem we're seeing is that running tests locally works, but on CI it fails with the error above. Any ideas where I screwed up dependency management?

**Comment by bobvawter** [comment]
I'm not sure what happens when you have both go modules and the vendor directory present simultaneously.  You might try removing the vendor dir (as well as the `Gopkg.*` files) and see what happens.

**Comment by rafiss** [comment]
Replaced by https://github.com/cockroachdb/examples-orms/pull/91

**Pull request closed without merging**
