### PR TITLE
rails: disable DDL transactions

### PR DESCRIPTION
**Pull request by dt**
Due to https://github.com/cockroachdb/cockroach/issues/16182, the FK doesn't see the indexes if in same txn,
so, as seen in schema.rb diff, it creates diplicative indexes

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/examples-orms/27)

### CODE REVIEW

**Comment by dt** [comment]
This should unblock https://github.com/cockroachdb/cockroach/pull/16175 I think

**Comment by tamird** [comment]
Don't we need to do this in our active record adapter?

**Comment by dt** [comment]
we don't _need_ to -- some combinations of schema changes and txns work fine -- but it might not be a terrible idea, though AFAIK, the goal is to just fix the strange DDL behaviors server side eventually.

anyway, I'll leave that debate to our orm compat experts.

**Comment by jordanlewis** [comment]
LGTM. Did Rails properly generate that updated schema.rb?

We should definitely disable DDLs in transactions in our adapter. I didn't know that was possible.

**Comment by dt** [comment]
yes, I only edited the migration, not the schema.rb.

**Pull request merged**
