### PR TITLE
hibernate: Setup initial project structure, schema, and db connection

### PR DESCRIPTION
**Pull request by nvanbenschoten**
This is currently blocked on use of **pg_catalog** in the JDBC Postgres driver's `getTables()` implementation. It was previously blocked on https://github.com/cockroachdb/cockroach/issues/7515, before https://github.com/cockroachdb/cockroach/pull/7686 addressed the issue.

### CODE REVIEW

**Comment by tamird** [comment]
What's the acceptance criteria here? We need some CI integration, I think.

**Comment by petermattis** [comment]
@mjibson Given your previous work on language acceptance tests, can you comment on the `examples-orms` structure?

**Comment by mjibson** [comment]
This organization and setup LGTM. It's hard to say much more until there's some more substantial work being done.

**Comment by cuongdo** [comment]
@nvanbenschoten can you merge this with perhaps a big disclaimer in the `README.md` file that support for Hibernate still incomplete? It'd be great if @jordanlewis could extend the example to uncover any more work we need to do to support Hibernate.

**Comment by nvanbenschoten** [comment]
I don't think any of the previous issues with merging this have been addressed so I'm hesitant unless others are ok with it. Can @jordanlewis work off of this branch instead?

**Pull request merged**
